version: '3.8'

services:
  app:
    image: checkinkids-api:latest
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: checkinkids-api
    ports:
      - ${PORT}:${PORT}
    restart: always
    env_file: .env